# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='return_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=True, help_text='Payment Status', max_length=200),
        ),
    ]
