# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170712_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_id',
            field=models.CharField(default=True, help_text='Card ID', max_length=200),
        ),
    ]
