# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='bookinstance',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookInstance'),
        ),
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=True, help_text='Enter number of Copies'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not Available'), ('a', 'Available')], default='d', help_text='Book availability', max_length=1),
        ),
    ]
