# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170705_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookinstance',
        ),
        migrations.AddField(
            model_name='book',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='imprint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Not Available'), ('a', 'Available')], default='d', help_text='Book availability', max_length=1),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
