# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170717_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/list-icons', verbose_name='Figure'),
        ),
    ]
