# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170705_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due_back',
        ),
    ]
