# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_due_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_id',
            field=models.CharField(default=True, help_text='Card ID', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='charge_id',
            field=models.CharField(default=True, help_text='Charge ID', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.IntegerField(default=True, help_text='Credit Card Details'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=True, help_text='Payment Status', max_length=200),
        ),
    ]
