# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_remove_book_due_back'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=True, help_text='Enter number of Copies')),
                ('price', models.IntegerField(default=True, help_text='Enter Daily rental Price')),
                ('book', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book')),
                ('order', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Order')),
                ('user', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
