# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
