# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170710_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
